[package]
name = "vkwh"
version = "0.1.0"
edition = "2021"

[dependencies]
winit = "0.26"

[dependencies.ash-window]
#version = "0.11"
git = "https://github.com/ash-rs/ash"

[dependencies.ash]
#version = "0.38"
git = "https://github.com/ash-rs/ash"
features = ["linked", "debug"]
